image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
      - target/apidocs/**/*

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r target/apidocs .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
