image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

pages-deploy:
  stage: deploy
  script:
  - mkdir .public
  - cp -r target/apidocs/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
